### ISSUE TITLE
execute mix ecto.setup failed

### ISSUE THREAD

**Issue by yingjingyang** [WeLightProject/tai-shang-nft-parser#1]
❯ mix ecto.setup

17:47:10.600 [error] GenServer #PID<0.307.0> terminating
** (UndefinedFunctionError) function :crypto.hmac/3 is undefined or private
    (crypto 5.0.4) :crypto.hmac(:sha256, "postgres", <<144, 50, 140, 131, 110, 6, 126, 40, 193, 142, 60, 198, 171, 100, 158, 225, 0, 0, 0, 1>>)
    (postgrex 0.15.0) lib/postgrex/scram.ex:52: Postgrex.SCRAM.hash_password/6
    (postgrex 0.15.0) lib/postgrex/scram.ex:26: Postgrex.SCRAM.verify/2
    (postgrex 0.15.0) lib/postgrex/protocol.ex:734: Postgrex.Protocol.auth_cont/4
    (postgrex 0.15.0) lib/postgrex/protocol.ex:579: Postgrex.Protocol.handshake/2
    (db_connection 2.4.0) lib/db_connection/connection.ex:82: DBConnection.Connection.connect/2
    (connection 1.1.0) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.16.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for TaiShangNftParser.Repo couldn't be created: killed

**Comment by leeduckgo** [comment]
solve by excute `mix deps.update --all`
